### ISSUE TITLE
cannot compile/open the example project

### ISSUE THREAD

**Issue by chakming** [lyahdav/LIYDateTimePicker#3] opened 2015-01-12 06:15 UTC
First of all, thanks a lot for making this awesome repo! 

I got this error when compiling the example project.

`ld: 91 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by lyahdav** [comment] 2015-01-12 07:13
Interesting, I can't reproduce this. I just tried to clone the repo, run `pod install` from the Example folder, open the xcworkspace, and run the project. I'm on Xcode 6.1.1 and cocoapods 0.34.2. What versions of these tools are you on? Could you maybe include more output from the error?

**Comment by chakming** [comment] 2015-01-12 07:23
Thanks for quick reply! Actually I've tried to import on my own and it works. But still not working for the project in 'Example' directory.

I'm using Xcode 6.1.1 and cocoapods 0.35.0, and here you go [the compile error gist file](https://gist.github.com/chakming/4756cc4a6840e6ac565d).

**Comment by richardoti** [comment] 2015-08-09 20:59
Having the same issue. Downloaded the repo, then `cd` to the Example folder, and run `pod install`, got this output:
```Ruby

[!] Invalid `LIYDateTimePicker.podspec` file: [!] Unsupported version requirements. Updating CocoaPods might fix the issue.

 #  from /Volumes/Data/LIYDateTimePicker-master/Example/Pods/Local Podspecs/LIYDateTimePicker.podspec:33
 #  -------------------------------------------
 #    # s.frameworks = 'SomeFramework', 'AnotherFramework'
 >    s.dependency 'MZDayPicker', :git => 'https://github.com/lyahdav/MZDayPicker/tree/hightlight_today'
 #  end
 #  -------------------------------------------
```

**Comment by lyahdav** [comment] 2015-10-03 18:39
Should be fixed in https://github.com/lyahdav/LIYDateTimePicker/commit/e7c50f683d1c182f8fab7852581b85057080a14e.

**Closed by lyahdav** 2015-10-03 18:39 UTC
